import enum
import secrets
import uuid
from datetime import datetime

from sqlalchemy import (
    Column, String, Integer, Boolean, DateTime, ForeignKey, Text, Enum
)
from sqlalchemy.orm import relationship

from app.database import Base


def gen_uuid() -> str:
    return str(uuid.uuid4())


def gen_share_token() -> str:
    # 32 bytes -> 43-char url-safe token. Unguessable capability token for
    # the client-facing read-only tracker link.
    return secrets.token_urlsafe(32)


class ProjectType(str, enum.Enum):
    landing_page = "landing_page"
    full_website = "full_website"
    web_app = "web_app"
    mobile_app = "mobile_app"
    branding = "branding"
    other = "other"


class ProjectStatus(str, enum.Enum):
    not_started = "not_started"
    in_progress = "in_progress"
    completed = "completed"
    on_hold = "on_hold"


class TaskStatus(str, enum.Enum):
    pending = "pending"
    in_progress = "in_progress"
    done = "done"


class User(Base):
    """The freelancer / account owner. Clients never get a User row —
    they access projects only via the unguessable share_token link."""
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=gen_uuid)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    is_active = Column(Boolean, default=True)

    projects = relationship("Project", back_populates="owner", cascade="all, delete-orphan")


class Project(Base):
    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=gen_uuid)
    owner_id = Column(String, ForeignKey("users.id"), nullable=False)

    client_name = Column(String, nullable=False)
    client_email = Column(String, nullable=True)

    title = Column(String, nullable=False)
    project_type = Column(Enum(ProjectType), nullable=False)
    description = Column(Text, nullable=False)
    num_pages = Column(Integer, nullable=True)  # relevant for websites
    duration_weeks = Column(Integer, nullable=False)
    duration_days = Column(Integer, default=0)  # extra days on top of weeks

    status = Column(Enum(ProjectStatus), default=ProjectStatus.not_started)
    share_token = Column(String, unique=True, index=True, default=gen_share_token)
    share_enabled = Column(Boolean, default=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    owner = relationship("User", back_populates="projects")
    tasks = relationship(
        "Task", back_populates="project",
        cascade="all, delete-orphan", order_by="Task.week_number, Task.order_in_week",
    )


class Task(Base):
    """A single task within a weekly milestone, generated by the LLM
    breakdown and editable afterward."""
    __tablename__ = "tasks"

    id = Column(String, primary_key=True, default=gen_uuid)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False)

    week_number = Column(Integer, nullable=False)
    order_in_week = Column(Integer, default=0)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    status = Column(Enum(TaskStatus), default=TaskStatus.pending)
    completed_at = Column(DateTime, nullable=True)
    evidence_url = Column(String, nullable=True)

    project = relationship("Project", back_populates="tasks")
